version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - run:
          name: Build application Docker image
          command: |
            docker build -t danielnaranjo/docker-angular .
